name: repair_schedule_app
description: A new Flutter project Repair schedule
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  google_fonts: ^3.0.1
  http: ^0.13.5
  flutter_svg: ^1.1.0


  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2
  google_maps_flutter: ^2.2.1
  flutter_polyline_points: ^0.2.6
  geolocator: ^7.7.1
  geocoding: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  assets:
    - assets/img/
    - assets/SVG/
  uses-material-design: true
